letsencrypt:
  build: .
  container_name: letsencrypt
  expose:
    - 80:80
  volumes:
    - /certs:/certs
  restart: always
  environment:
    - DOMAINS=competency.nu
    - EMAIL=christian@landgren.nu
